FROM postgres:15

RUN apt-get update && apt-get -y install git make gcc libpq-dev
RUN apt-get update && apt-get -y install git make gcc libpq-dev postgresql-server-dev-15

RUN cd /tmp && \
    git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git && \
    cd pgvector && \
    make && \
    make install