"""file_name

Revision ID: a669801236c0
Revises: 9c8c634fd5f1
Create Date: 2023-12-21 23:42:18.103684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a669801236c0'
down_revision: Union[str, None] = '9c8c634fd5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('files', 'name')
    # op.create_table('langchain_pg_embedding',
    # sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('embedding', pgvector.sqlalchemy.Vector(), autoincrement=False, nullable=True),
    # sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    # sa.Column('custom_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name='langchain_pg_embedding_collection_id_fkey', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('uuid', name='langchain_pg_embedding_pkey')
    # )
    # op.create_table('langchain_pg_collection',
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    # sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('uuid', name='langchain_pg_collection_pkey')
    # )
    # ### end Alembic commands ###
